const fs = require('fs');
const path = require('path');
const vm = require('vm');
const { decodeChromiumClone } = require('./decode_chromium_clone.js');
const { buildContext } = require('./app_source.js');

const sourcePath = process.argv[2];
const archivePath = process.argv[3] || path.join(__dirname, '..', 'Jane Harlow.horde_human');
const bundlePath = process.argv[4] || path.join(__dirname, '..', 'jane-harlow-human.js');

if (!sourcePath) {
  throw new Error('Usage: node build_jane_human.js CHROMIUM_BLOB [ARCHIVE] [BUNDLE]');
}

const decoded = decodeChromiumClone(fs.readFileSync(sourcePath)).value;
const recovered = Array.isArray(decoded) && decoded.length === 1 ? decoded[0] : decoded;
if (!recovered || recovered.name !== 'Jane Harlow') {
  throw new Error(`Expected Jane Harlow, found ${recovered?.name || 'no character'}`);
}

const context = {
  console: { warn() {}, log() {} },
  state: {
    globalSettings: { apiProvider: 'openrouter' },
    personas: [], companions: [], companionThreads: {}, companionTimelines: {}
  },
  companionMcpToolCatalog: { higgsfield: [], magnific: [] }
};
buildContext(vm, ['buildCompanionShareData'], context);

// Use Horde Studio's real sharing boundary. It retains authored identity and
// Active Life design while resetting mood, memories, usage, events and every
// other piece of history accumulated during the original browser session.
const companion = context.buildCompanionShareData(recovered, Date.now());
const archive = {
  _format: 'horde-studio-virtual-human',
  _version: 2,
  _kind: 'character',
  _exportedAt: new Date().toISOString(),
  companion
};
const bundle = {
  ...archive,
  bundledId: 'jane-harlow-v1'
};

fs.writeFileSync(archivePath, `${JSON.stringify(archive, null, 2)}\n`);
fs.writeFileSync(bundlePath,
  `// Generated by scratch/build_jane_human.js. Keep the standalone archive as the source artifact.\n` +
  `globalThis.HORDE_INCLUDED_HUMANS = [\n` +
  `  ...(globalThis.HORDE_INCLUDED_HUMANS || []),\n` +
  `  ${JSON.stringify(bundle)}\n` +
  `];\n`);

process.stdout.write(`${JSON.stringify({
  name: companion.name,
  archivePath,
  bundlePath,
  profilePhotoBytes: companion.profilePhoto.length,
  basePhotoBytes: companion.basePhoto.length,
  places: companion.lifeProfile.places.length,
  socialCircle: companion.lifeProfile.socialCircle.length,
  weeklySchedule: companion.lifeProfile.weeklySchedule.length,
  wildcardDeck: companion.lifeProfile.wildcardDeck.length,
  memories: companion.memory.longTerm.length,
  lifeEvents: companion.lifeEvents.length,
  textTurns: companion.usage.textTurns
}, null, 2)}\n`);
